name: Sync Docs to Wiki

on:
  push:
    paths:
      - "docs/**"
    branches:
      - main
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Clone the wiki repository
        run: |
          git clone "https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.wiki.git" wiki

      - name: Verify wiki clone
        run: |
          echo "Checking if wiki/.git exists:"
          ls -la wiki/
          if [ ! -d "wiki/.git" ]; then
            echo "ERROR: wiki/.git directory not found!"
            exit 1
          fi

      - name: Copy docs to wiki (excluding README.md)
        run: |
          # Copy all files except README.md, overwriting existing files
          cd docs
          for file in *.md; do
            if [ "$file" != "README.md" ] && [ -f "$file" ]; then
              echo "Copying: $file"
              cp "$file" ../wiki/
            fi
          done
          cd ..

      - name: Ensure Home.md exists
        run: |
          if [ ! -f "wiki/Home.md" ]; then
            echo "ERROR: docs/Home.md not found!"
            exit 1
          fi

      - name: Commit and push to wiki
        run: |
          cd wiki

          # Configure git
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          # Add all files
          git add -A

          # Check if there are changes to commit
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Sync docs from main repo

            Source: ${{ github.repository }}@${{ github.sha }}
            Triggered by: ${{ github.event_name }}"
            
            git push
          fi
