name: Example

on:
  push:
    paths:
      - "docs/**"
    branches:
      - main
  pull_request:
    paths:
      - "docs/**"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  # Dry run for pull requests
  dry-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Dry Run Sync
        uses: ./
        with:
          github-token: ${{ github.token }}
          dry-run: "true"
